//! 图标资产集成(SerialHub 同款 **存在才嵌入** 模式):
//!
//! 1. exe 图标(仅 Windows 目标,winres 嵌 assets/app.ico);
//! 2. 托盘图标 assets/app-32.png 与窗口图标 assets/app-128.png 在**构建期**解码成
//!    原始 RGBA 写进 OUT_DIR(运行时零解码依赖:gui.rs 直接 Icon::from_rgba),
//!    缺资产 → 对应常量为 None(运行时回退程序画的圆点);
//! 3. 生成 OUT_DIR/embedded_icons.rs 供 src/gui.rs include!
//!    (无论资产是否齐全都写出该文件,include! 永不失败)。

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=assets");
    println!("cargo:rerun-if-changed=build.rs");

    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();

    // exe 图标:winres 仅对 Windows 目标执行(非 Windows 目标不引用 winres 逻辑)
    let ico = Path::new("assets/app.ico");
    if target_os == "windows" && ico.exists() {
        if let Err(e) = winres::WindowsResource::new()
            .set_icon("assets/app.ico")
            .compile()
        {
            println!(
                "cargo:warning=mini-rtt-viewer: app.ico 嵌入失败(忽略, exe 无自定义图标): {e}"
            );
        }
    }

    // 解码 RGBA(构建期;失败一律回退 None,不阻塞构建)
    let window = decode_png(Path::new("assets/app-128.png"));
    let tray = decode_png(Path::new("assets/app-32.png"));
    // 未连接态的托盘变体:构建期按亮度灰化(运行时零解码/零分配)
    let tray_gray = tray.as_ref().map(|(rgba, w, h)| gray_rgba(rgba, *w, *h));

    // 生成嵌入清单(恒定写出)
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let gen = |payload: &Option<(Vec<u8>, u32, u32)>, name: &str| -> String {
        match payload {
            Some((rgba, w, h)) => {
                let bin = out_dir.join(format!("{name}.rgba"));
                fs::write(&bin, rgba)
                    .unwrap_or_else(|e| panic!("写 OUT_DIR/{name}.rgba 失败: {e}"));
                format!(
                    "pub(crate) const {name}: Option<RgbaIcon> = \
                     Some((include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{name}.rgba\")), {w}, {h}));\n"
                )
            }
            None => format!("pub(crate) const {name}: Option<RgbaIcon> = None;\n"),
        }
    };
    let mut code = String::from("// @generated by build.rs —— 资产存在才嵌入, 请勿手改\n");
    code.push_str("pub(crate) type RgbaIcon = (&'static [u8], u32, u32);\n");
    code.push_str(&gen(&window, "WINDOW_ICON_RGBA"));
    code.push_str(&gen(&tray, "TRAY_ICON_RGBA"));
    code.push_str(&gen(&tray_gray, "TRAY_ICON_GRAY_RGBA"));
    fs::write(out_dir.join("embedded_icons.rs"), code).expect("写 embedded_icons.rs 失败");
}

/// 亮度灰化(保留 alpha 与原尺寸):未连接态托盘图标,与彩色版共用一份源资产。
fn gray_rgba(rgba: &[u8], w: u32, h: u32) -> (Vec<u8>, u32, u32) {
    let mut out = Vec::with_capacity(rgba.len());
    for p in rgba.as_chunks::<4>().0 {
        let l = (u32::from(p[0]) * 299 + u32::from(p[1]) * 587 + u32::from(p[2]) * 114) / 1000;
        out.extend_from_slice(&[l as u8, l as u8, l as u8, p[3]]);
    }
    (out, w, h)
}

fn decode_png(path: &Path) -> Option<(Vec<u8>, u32, u32)> {
    let bytes = fs::read(path).ok()?;
    let mut dec = png::Decoder::new(std::io::Cursor::new(&bytes[..]));
    dec.set_transformations(png::Transformations::EXPAND); // 调色板/灰度 → RGB(A)
    let mut rdr = dec.read_info().ok()?;
    let mut buf = vec![0u8; rdr.output_buffer_size()];
    let info = rdr.next_frame(&mut buf).ok()?;
    let (w, h) = (info.width, info.height);
    if w == 0 || h == 0 || (w as u64) * (h as u64) > 4096 * 4096 {
        return None;
    }
    if info.bit_depth != png::BitDepth::Eight {
        return None;
    }
    let (color, _depth) = rdr.output_color_type();
    let raw = &buf[..info.buffer_size()];
    let rgba = match color {
        png::ColorType::Rgba => raw.to_vec(),
        png::ColorType::Rgb => {
            let mut v = Vec::with_capacity(raw.len() / 3 * 4);
            for px in raw.as_chunks::<3>().0 {
                v.extend_from_slice(px);
                v.push(255);
            }
            v
        }
        _ => return None,
    };
    if rgba.len() != (w as usize) * (h as usize) * 4 {
        return None;
    }
    Some((rgba, w, h))
}
